"""Theorem 3: when the invariant / equivariant split of a representation is unique.

A representation that factorises as "pathology content" (invariant) plus "pose"
(equivariant) is only meaningful if the factorisation is *identifiable*.  Classical
invariant theory settles this completely for the dipole model.

Let ``V = [v(t_1), ..., v(t_m)] in R^{3 x m}`` be the VCG trajectory.  The first
fundamental theorem for ``O(3)`` says the ring of invariants of ``m`` vectors is
generated by the pairwise inner products, i.e. by the **Gram matrix**
``G = V^T V``; for ``SO(3)`` one must adjoin the signed triple products
``det[v_i, v_j, v_k]``.  Consequently:

* ``rank(V) = 3``  -- Gram matrix plus a single non-zero triple product determine
  the ``SO(3)`` orbit uniquely, and the stabiliser is trivial, so the pose ``R`` is
  recoverable exactly.
* ``rank(V) = 2``  -- the loop is planar.  The stabiliser is still trivial, so ``R``
  is recoverable, but every triple product vanishes and the Gram matrix determines
  the configuration only up to ``O(3)``: a mirrored VCG loop is indistinguishable.
  This is the clinically relevant caveat, planar QRS loops being common.
* ``rank(V) = 1``  -- a collinear trajectory has an ``SO(2)`` stabiliser and one
  pose angle is fundamentally unrecoverable.

The Gram matrix is therefore a *complete and lossless* invariant descriptor on the
rank-3 stratum: pooling through it discards exactly the nuisance and nothing else,
unlike the ad-hoc global pooling used by non-equivariant encoders.
"""

from __future__ import annotations

import numpy as np

__all__ = [
    "gram_invariant",
    "triple_products",
    "recover_rotation",
    "trajectory_rank",
    "identifiability_report",
]


def gram_invariant(V: np.ndarray) -> np.ndarray:
    """Gram matrix ``V^T V`` of a ``(..., 3, m)`` set of vectors -- an ``O(3)`` invariant."""
    return np.einsum("...it,...is->...ts", V, V)


def triple_products(V: np.ndarray, index_triples: np.ndarray | None = None) -> np.ndarray:
    """Signed volumes ``det[v_i, v_j, v_k]`` -- the pseudo-scalars that break ``O(3)`` to ``SO(3)``."""
    m = V.shape[-1]
    if index_triples is None:
        index_triples = np.array(
            [(i, j, k) for i in range(m) for j in range(i + 1, m) for k in range(j + 1, m)]
        )
    cols = V[..., index_triples]                      # (..., 3, n_triples, 3)
    cols = np.moveaxis(cols, -3, -1)                  # (..., n_triples, 3, 3)
    return np.linalg.det(cols)


def trajectory_rank(V: np.ndarray, tol: float = 1e-8) -> int:
    """Numerical rank of the VCG trajectory -- the stratum that Theorem 3 keys on."""
    s = np.linalg.svd(V, compute_uv=False)
    return int(np.sum(s > tol * max(s[0], 1e-30)))


def recover_rotation(V_ref: np.ndarray, V_obs: np.ndarray, allow_reflection: bool = False):
    """Orthogonal Procrustes (Kabsch): the ``R`` minimising ``||R V_ref - V_obs||_F``.

    With ``allow_reflection=False`` the result is constrained to ``SO(3)``, which is
    the physically meaningful choice -- a reflection of the heart vector is not a
    posture change.
    """
    H = V_obs @ V_ref.T
    U, _, Vt = np.linalg.svd(H)
    R = U @ Vt
    if not allow_reflection and np.linalg.det(R) < 0:
        U[:, -1] *= -1.0
        R = U @ Vt
    return R


def identifiability_report(
    ranks: tuple[int, ...] = (3, 2, 1),
    m: int = 64,
    noise_levels: tuple[float, ...] = (0.0, 0.01, 0.05),
    n_trials: int = 64,
    seed: int = 0,
) -> list[dict]:
    """Empirical confirmation of the three strata of Theorem 3.

    For each trajectory rank and noise level, a random trajectory is rotated by a
    known ``R``, the pose is re-estimated from the observed trajectory, and three
    quantities are reported:

    ``pose_error_deg``
        geodesic error of the recovered rotation -- near zero for rank >= 2, large
        and unidentifiable for rank 1.
    ``gram_mismatch``
        ``||G_obs - G_ref||`` -- zero up to noise for all ranks, confirming the Gram
        matrix is genuinely invariant.
    ``chirality_gap``
        relative magnitude of the largest triple product; it collapses to zero for
        planar loops, which is exactly the ``O(3)`` / ``SO(3)`` ambiguity.
    """
    from eqecg.group import geodesic_distance, random_rotation

    rng = np.random.default_rng(seed)
    rows: list[dict] = []
    for rank in ranks:
        for sigma in noise_levels:
            pose_err, gram_err, chir = [], [], []
            for _ in range(n_trials):
                coeff = rng.normal(size=(rank, m))
                basis = np.linalg.qr(rng.normal(size=(3, 3)))[0][:, :rank]
                V = basis @ coeff
                V /= np.linalg.norm(V)
                R = random_rotation(rng)
                V_obs = R @ V + sigma * rng.normal(size=V.shape)
                R_hat = recover_rotation(V, V_obs)
                pose_err.append(np.rad2deg(geodesic_distance(R, R_hat)))
                gram_err.append(
                    np.linalg.norm(gram_invariant(V_obs) - gram_invariant(V))
                    / np.linalg.norm(gram_invariant(V))
                )
                tp = triple_products(V, np.array([[0, 1, 2]]))
                chir.append(float(np.abs(tp).max()) / (np.linalg.norm(V[:, :3]) ** 3 + 1e-12))
            rows.append(
                {
                    "trajectory_rank": rank,
                    "noise_sigma": sigma,
                    "pose_error_deg_mean": float(np.mean(pose_err)),
                    "pose_error_deg_p95": float(np.percentile(pose_err, 95)),
                    "gram_relative_error": float(np.mean(gram_err)),
                    "chirality_signal": float(np.mean(chir)),
                }
            )
    return rows
