#!/usr/bin/env python3
"""Write ``results/SUMMARY.md``: a plain-language digest of every experiment.

The LaTeX tables are for the paper; this is for reading. It also states, for each
hypothesis, whether the evidence supports it, supports it only in part, or
contradicts it -- so the answer is recorded next to the numbers rather than left to
whoever writes the discussion section.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def load(name: str):
    p = RESULTS / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else None


def agg(rows, keys, value):
    acc = defaultdict(list)
    for r in rows:
        if value in r and r[value] is not None:
            acc[tuple(r[k] for k in keys)].append(r[value])
    return {k: float(np.mean(v)) for k, v in acc.items()}


def main() -> None:
    out: list[str] = ["# Results summary", ""]
    out.append("Generated by `scripts/summarize.py` from `results/*.json`. "
               "All empirical numbers are on simulated data (see README).")
    out.append("")

    if (d := load("theory")):
        out += ["## Theory (exact, verified numerically)", ""]
        for name, v in d["theorem1_geometry"].items():
            out.append(
                f"- **{name.capitalize()}**: ranks {v['rank_dipolar']}/"
                f"{v['rank_residual']}/{v['rank_realisable']} (dipolar/residual/"
                f"realisable), kappa(D)={v['anisotropy_kappa_D']:.3f}, "
                f"kappa(M)={v['metric_condition_number']:.3f}; Euclidean "
                f"orthogonality defect {v['max_euclidean_orthogonality_defect']:.3f} "
                f"vs M-invariance defect {v['max_M_invariance_defect']:.1e}."
            )
        dims = d["theorem1_intertwiner_dimensions"]
        ok = all(r["numerical_dimension"] == r["schur_prediction"] for r in dims)
        out.append(f"- **Theorem 1 (equivariant maps)**: numerical dimension matches "
                   f"the Schur prediction for all {len(dims)} channel configurations "
                   f"tested — {'YES' if ok else 'NO'}.")
        rey = d["theorem2_reynolds"]
        out.append(
            f"- **Theorem 2 (where the proof breaks)**: the Reynolds operator is a "
            f"projection in both geometries (trace {rey['M']['trace']:.0f} either way) "
            f"but has asymmetry {rey['euclidean']['relative_asymmetry']:.3f} in the "
            f"Euclidean inner product and {rey['M']['relative_asymmetry']:.1e} in the "
            f"gauge. This is the precise failure point."
        )
        if "theorem2_norm_distortion" in d:
            c = ", ".join(f"k={r['degree']}: {r['condition_number']:.2f}"
                          for r in d["theorem2_norm_distortion"])
            out.append(f"- **Theorem 2 transport constant**: {c}.")
        deg2 = [r for r in d["theorem2_dimension_table"]
                if r["degree"] == 2 and r["time_samples"] == 1]
        if deg2:
            out.append(f"- **Dimension removed** (degree-2 features, one time sample): "
                       f"{100*deg2[0]['fraction_removed']:.1f}% "
                       f"({deg2[0]['dim_invariant']} of {deg2[0]['dim_total']} survive).")
        for r in d["theorem3_identifiability"]:
            if r["noise_sigma"] == 0.0:
                out.append(f"- **Theorem 3, rank {r['trajectory_rank']}**: pose error "
                           f"{r['pose_error_deg_mean']:.3f} deg, chirality signal "
                           f"{r['chirality_signal']:.4f}.")
        out.append("")

    if (d := load("equivariance")):
        out += ["## Measured equivariance error (untrained weights)", ""]
        for arch, regimes in d["architectures"].items():
            m = regimes.get("haar_rotation", {})
            out.append(f"- `{arch}`: relative logit error "
                       f"{m.get('relative_logit_error_max', float('nan')):.2e}, pose "
                       f"error {m.get('pose_equivariance_error_deg_max', float('nan')):.1f} deg "
                       f"(Haar).")
        for kind, v in d["lead_reversal_vs_group"].items():
            out.append(f"- Lead reversal `{kind}` is at relative distance "
                       f"{v['residual_to_nearest_group_element']:.2f} from the nearest "
                       f"group element, so H3 is a genuine out-of-group test.")
        out.append("")

    if (d := load("h1_sample_efficiency")):
        rows = d["rows"]
        a = agg(rows, ("model", "n_train"), "test_macro_f1")
        sizes = sorted({r["n_train"] for r in rows})
        models = sorted({r["model"] for r in rows})
        out += ["## H1: sample efficiency", "",
                "| model | " + " | ".join(f"n={n}" for n in sizes) + " |",
                "|---|" + "---|" * len(sizes)]
        for m in models:
            out.append(f"| {m} | " + " | ".join(
                f"{a[(m,n)]:.3f}" if (m, n) in a else "–" for n in sizes) + " |")
        best_other = {n: max((a[(m, n)] for m in models if m != "equivariant"
                              and (m, n) in a), default=float("nan")) for n in sizes}
        wins = [n for n in sizes if ("equivariant", n) in a
                and a[("equivariant", n)] > best_other[n]]
        out += ["", f"**Verdict:** the equivariant model beats every baseline at "
                    f"n ∈ {wins if wins else '(none)'} and loses at the remaining sizes. "
                    "H1 as stated (a 10–100x data multiplier across the board) is "
                    "**not supported**; a low-data advantage is."]
        mult = load("h1_data_multiplier")
        if mult:
            finite = [m for m in mult if np.isfinite(m["multiplier"]) and m["multiplier"] > 1]
            if finite:
                best = max(finite, key=lambda m: m["multiplier"])
                out.append(f"Largest observed data multiplier: {best['multiplier']:.1f}x "
                           f"({best['baseline']} at n={best['n_train']}).")
        out.append("")

    if (d := load("h2_h3_probe_robustness")):
        a = agg(d["probes"], ("model", "target"), "r2_mean")
        out += ["## H2 / Proposition 4: nuisance leakage (linear probe R^2)", ""]
        for (m, t), v in sorted(a.items()):
            out.append(f"- `{m}` → {t}: R² = {v:.3f}")
        rot = {m: v for (m, t), v in a.items() if t == "rotation_vector"}
        leaky = [m for m, v in rot.items() if v > 0.5]
        out += ["", f"**Verdict:** H2 predicted R² > 0.5 for non-equivariant encoders; "
                    f"observed for {leaky if leaky else '(none)'}.", ""]

        r = d["robustness"]
        b = agg(r, ("model", "corruption", "strength"), "macro_f1")
        out += ["## H3: robustness (test macro-F1)", ""]
        keys = sorted({(x["corruption"], str(x["strength"])) for x in r})
        models = sorted({x["model"] for x in r})
        out += ["| model | " + " | ".join(f"{c}:{s}" for c, s in keys) + " |",
                "|---|" + "---|" * len(keys)]
        for m in models:
            cells = []
            for c, s in keys:
                hit = [v for (mm, cc, ss), v in b.items()
                       if mm == m and cc == c and str(ss) == s]
                cells.append(f"{hit[0]:.3f}" if hit else "–")
            out.append(f"| {m} | " + " | ".join(cells) + " |")
        out.append("")

    if (d := load("h4_dipole_breakdown")):
        a = agg(d["nondipolar_sweep"], ("model", "nondipolar_fraction"), "macro_f1")
        fr = sorted({r["nondipolar_fraction"] for r in d["nondipolar_sweep"]})
        out += ["## H4: dipole breakdown", "",
                "| model | " + " | ".join(f"eta={f}" for f in fr) + " |",
                "|---|" + "---|" * len(fr)]
        for m in sorted({r["model"] for r in d["nondipolar_sweep"]}):
            out.append(f"| {m} | " + " | ".join(
                f"{a[(m,f)]:.3f}" if (m, f) in a else "–" for f in fr) + " |")
        b = agg(d["pose_dependent_labels"], ("model",), "recall_AXIS")
        out += ["", "### Pose-defined AXIS class (a strictly invariant model cannot "
                    "represent it)", ""]
        for (m,), v in sorted(b.items()):
            out.append(f"- `{m}`: AXIS recall {v:.3f}")
        out.append("")

    for name, title, keys in (
        ("capacity_ablation", "## Capacity ablation", ("model", "width")),
        ("noise_frame", "## Noise frame", ("noise_frame", "model", "n_train")),
        ("lr_fairness", "## Learning-rate fairness", ("model", "n_train", "lr")),
    ):
        if (d := load(name)):
            a = agg(d["rows"], keys, "macro_f1")
            out += [title, ""]
            for k, v in sorted(a.items(), key=lambda kv: str(kv[0])):
                out.append(f"- {' / '.join(str(x) for x in k)}: {v:.3f}")
            out.append("")

    path = RESULTS / "SUMMARY.md"
    path.write_text("\n".join(out) + "\n")
    print(f"[written] {path}")


if __name__ == "__main__":
    main()
